### ISSUE TITLE
Transfer部分文档能具体讲解一下吗？

### ISSUE THREAD

**Issue by hexisyztem** [yang-er/dj_helper#1]
Transfer部分的文档因为过于简洁，遇到报错不知所措。。。（另，求QQ好友位

**Comment by yang-er** [comment]
我的QQ：670171961 QAQ我估计你的报错应该是比赛开始前的，比赛开始后再启动就不会报错了

**Comment by hexisyztem** [comment]
我之前没有编译Transfer.csproj文件，刚才csc Transfer.csproj 编译后得到一个 Transfer，但是有点问题。。。（之前没有了解过C#。。。不是很懂要怎么操作。。。
另，我是蔡队介绍过来看老哥你的github的（笑
